### ISSUE TITLE
Orders are being auto-submitted to Siftscience

### ISSUE THREAD

**Issue by Fidyyuan** [Fermiac/woocommerce-siftscience#58]
It seems that even though the "Automatically send data to SiftScience when an order is created" box is not checked, they're being sent to Siftscience automatically. The plugin still lists that orders are not backfilled but they've already been sent.

When I click "Back-Fill", it tell me "Error: SyntaxError: Unexpected token < in JSON at position 0"

**Comment by nabsul** [comment]
@Fidyyuan 

FYI: This was because I had blocked the $create_order event from going to sift science, but there were still $update_order and $order_status events that were still going out, and those will create an order in sift science.

It's important to note though, that if you don't auto-send, sift science's machine learning algorithms might be losing important and useful information to become more accurate.
